--- 
services: 
  product-service: 
    build: ./product
    ports: 
      - "5001:80"
    volumes: 
      - "./product:/usr/src/app"
  website: 
    depends_on: 
      - product-service
    image: "php:apache"
    ports: 
      - "5000:80"
    volumes: 
      - "./website:/var/www/html"
version: "3"
