version: '3'

services:
    Product-service:
        build: ./ressources
        volumes:
            - ./ressources:/usr/src/app
        ports:
            - 5001:80
            
    website:
        image: php:apache
        volumes:
            - ./main-page:/var/www/html
        ports:
            - 5000:80
        depends_on:
            - product-service